
package com.mycompany.testejogovelha;


public class Jogo extends javax.swing.JFrame {
public boolean jogador1 = false;
public boolean jogador2 = false;
public int linha=0,coluna=0;
public int contjogada=0;
int vez;
public String linha1,linha2,linha3,coluna1,coluna2,coluna3,diagonal1,diagonal2;
String[][]posicaomatriz=new String[3][3];
    
    public Jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtvisor = new javax.swing.JTextArea();
        btnreiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Velha");

        btn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        txtvisor.setColumns(20);
        txtvisor.setRows(5);
        jScrollPane1.setViewportView(txtvisor);

        btnreiniciar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnreiniciar.setText("REINICIAR");
        btnreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnreiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnreiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void vezjogador(){
    if (jogador1==true&&jogador2==true) {
        this.vez=1;
        jogador1=false;
        jogador2=true;
        txtvisor.setText("Vez do Jogador O");
        vez++;
        //se o jogador2 for false significa que o ultimo foi X
    }else if (jogador1==true&&jogador2==false){
        this.vez=1;
        jogador1=false;
        jogador2=true;
        txtvisor.setText("Vez do Jogador O");
        vez++;
    }else{
        this.vez=2;
        jogador1=true;
        jogador2=false;
        txtvisor.setText("Vez do Jogador X");
        vez--;
        }
}
    public void Fecharbotoes(){
    btn1.setEnabled(false);
    btn2.setEnabled(false);
    btn3.setEnabled(false);
    btn4.setEnabled(false);
    btn5.setEnabled(false);
    btn6.setEnabled(false);
    btn7.setEnabled(false);
    btn8.setEnabled(false);
    btn9.setEnabled(false);  
    }
    public void limparmatriz() {
        for (linha = 0; linha < 3; linha++) {
            for (coluna = 0; coluna < 3; coluna++) {
                posicaomatriz[linha][coluna] = "";
            }
        }
    }
public void verificaposicoes(){
    contjogada=0;
    for(linha=0;linha<3;linha++){
        for(coluna=0;coluna<3;coluna++){
          if(posicaomatriz[linha][coluna]=="x"|posicaomatriz[linha][coluna]=="o"){
             contjogada+=1;
             System.out.println(contjogada);
          }
        }
        }
}
public void vencedor(){
        linha1=posicaomatriz[0][0]+posicaomatriz[0][1]+posicaomatriz[0][2];
        linha2=posicaomatriz[1][0]+posicaomatriz[1][1]+posicaomatriz[1][2];
        linha3=posicaomatriz[2][0]+posicaomatriz[2][1]+posicaomatriz[2][2];
   
        coluna1=posicaomatriz[0][0]+posicaomatriz[1][0]+posicaomatriz[2][0];
        coluna2=posicaomatriz[0][1]+posicaomatriz[1][1]+posicaomatriz[2][1];
        coluna3=posicaomatriz[0][2]+posicaomatriz[1][2]+posicaomatriz[2][2];
   
        diagonal1=posicaomatriz[0][0]+posicaomatriz[1][1]+posicaomatriz[2][2];
        diagonal2=posicaomatriz[0][2]+posicaomatriz[1][1]+posicaomatriz[2][0];
        
    if(linha1.equals("xxx")||linha2.equals("xxx")||linha3.equals("xxx")
            ||coluna1.equals("xxx")||coluna2.equals("xxx")||coluna3.equals("xxx")
            ||diagonal1.equals("xxx")||diagonal2.equals("xxx")){
        Fecharbotoes();
        txtvisor.setText("O vencedor é o jogador X");
        //txtvisor2.setText();

    }else if(linha1.equals("ooo")||linha2.equals("ooo")||linha3.equals("ooo")
            ||coluna1.equals("ooo")||coluna2.equals("ooo")||coluna3.equals("ooo")
            ||diagonal1.equals("ooo")||diagonal2.equals("ooo")){
        Fecharbotoes();
    txtvisor.setText("O vencedor é o jogador O");
    }else if(contjogada==9){
        txtvisor.setText("Deu Velha");
    }
}
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // botao1
        vezjogador();
           if(vez==1){
        btn1.setText("X");
        posicaomatriz[0][0]="x";
        }else{
        btn1.setText("O");
        posicaomatriz[0][0]="o";
        }
        btn1.setEnabled(false);
        verificaposicoes();
        vencedor();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // botao2
        vezjogador();
       if(vez==1){
        btn2.setText("X");
        posicaomatriz[0][1]="x";
        }else{
        btn2.setText("O");
        posicaomatriz[0][1]="o";
        }
        btn2.setEnabled(false);        
        verificaposicoes();
        vencedor();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // botao3
        vezjogador();
       if(vez==1){
        btn3.setText("X");
        posicaomatriz[0][2]="x";
        }else{
        btn3.setText("O");
        posicaomatriz[0][2]="o";
        }
        btn3.setEnabled(false);
        verificaposicoes();
        vencedor();        
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        //botao4
        vezjogador();
        if(vez==1){
        btn4.setText("X");
        posicaomatriz[1][0]="x";
        }else{
        btn4.setText("O");
        posicaomatriz[1][0]="o";
        }
        btn4.setEnabled(false);        
        verificaposicoes();
        vencedor();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // botao5
        vezjogador();
        if(vez==1){
        btn5.setText("X");
        posicaomatriz[1][1]="x";
        }else{
        btn5.setText("O");
        posicaomatriz[1][1]="o";
        }
        btn5.setEnabled(false);        
        verificaposicoes();
        vencedor();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // botao6
        vezjogador();
        if(vez==1){
        btn6.setText("X");
        posicaomatriz[1][2]="x";
        }else{
        btn6.setText("O");
        posicaomatriz[1][2]="o";
        }
        btn6.setEnabled(false);
        verificaposicoes();
        vencedor();        
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // botao 7
        vezjogador();
        if(vez==1){
        btn7.setText("X");
        posicaomatriz[2][0]="x";
        }else{
        btn7.setText("O");
        posicaomatriz[2][0]="o";
        }
        btn7.setEnabled(false);
        verificaposicoes();
        vencedor();        
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // botao8
        vezjogador();
        if(vez==1){
        btn8.setText("X");
        posicaomatriz[2][1]="x";
        }else{
        btn8.setText("O");
        posicaomatriz[2][1]="o";
        }
        btn8.setEnabled(false);
        verificaposicoes();
        vencedor();        
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // botao9
        vezjogador();
        if(vez==1){
        btn9.setText("X");
        posicaomatriz[2][2]="x";
        }else{
        btn9.setText("O");
        posicaomatriz[2][2]="o";
        }
        btn9.setEnabled(false);
        verificaposicoes();
        vencedor();        
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreiniciarActionPerformed
        // reiniciar
        btn1.setText("");
        btn1.setEnabled(true);
        btn2.setText("");
        btn2.setEnabled(true);
        btn3.setText("");
        btn3.setEnabled(true);
        btn4.setText("");
        btn4.setEnabled(true);
        btn5.setText("");
        btn5.setEnabled(true);
        btn6.setText("");
        btn6.setEnabled(true);
        btn7.setText("");
        btn7.setEnabled(true);
        btn8.setText("");
        btn8.setEnabled(true);
        btn9.setText("");
        btn9.setEnabled(true);   
        limparmatriz();
        txtvisor.setText("");
        jogador1=false;
        jogador2=false;
    }//GEN-LAST:event_btnreiniciarActionPerformed

    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnreiniciar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtvisor;
    // End of variables declaration//GEN-END:variables
}
